lib: [
  "/home/d4hines/repos/hello-dream/_esy/default/store/b/debugging_gcc_issues-f5ee1aa3/install/default/lib/hello/META"
  "/home/d4hines/repos/hello-dream/_esy/default/store/b/debugging_gcc_issues-f5ee1aa3/install/default/lib/hello/dune-package"
  "/home/d4hines/repos/hello-dream/_esy/default/store/b/debugging_gcc_issues-f5ee1aa3/install/default/lib/hello/opam"
]
bin: [
  "/home/d4hines/repos/hello-dream/_esy/default/store/b/debugging_gcc_issues-f5ee1aa3/install/default/bin/hello"
]
doc: [
  "/home/d4hines/repos/hello-dream/_esy/default/store/b/debugging_gcc_issues-f5ee1aa3/install/default/doc/hello/README.md"
]
